config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }

  resources :articles do
    resource :comments, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { in: 3..140 }
  validates :text, presence: true, length: { in: 3..4000 }
  has_many :comments

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { in: 2..1000 }
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article

    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article

    else
      render action: 'edit'
    end    
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path      
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @cmt = @article.comments.new(comment_params)
    @cmt.author = current_user.username
    @cmt.save

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/edit.html.erb
<h3><%= t('articles.edit article') %></h3>

<%= form_for :article , url: article_path(@article), method: :put do |f| %>

	<div>
		<%= f.label :title %> <br />
		<%= f.text_field :title %>
	</div>

	<br />

	<div>
		<%= f.label :text %> <br />
		<%= f.text_area :text %>
	</div>	

	<br />

	<div>
		<%= f.submit %> <br />
	</div>	

<% end %>

app/views/articles/index.html.erb
<h2><%= t('articles.articles') %></h2>

<br />
	
<% @articles.each do |article| %>
		<h3><%= link_to article.title, article_path(article) %></h3>
		<p><%= article.text %></p>

		<p>
			<%= link_to t('articles.show'), article_path(article) %> |
			<%= link_to t('articles.edit'), edit_article_path(article) %> |
			<%= link_to t('articles.delete'), article_path(article), method: :delete, data: {confirm: t('articles.deleting')} %>
		</p>

<hr />
<% end %>

app/views/articles/new.html.erb
<h3><%= t('articles.new article') %></h3>

<%= form_for :article , url: articles_path do |f| %>

	<div>
		<%= f.label :title %> <br />
		<%= f.text_field :title %>
	</div>

	<br />

	<div>
		<%= f.label :text %> <br />
		<%= f.text_area :text %>
	</div>	

	<br />

	<div>
		<%= f.submit %> <br />
	</div>	

<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p><%= @article.text %></p>

<br />  <br /> 
<h3><%= t('articles.comments') %></h3>

<% @article.comments.each do |comment| %>
	<h4><%= comment.author %></h4>
	<p style="font-size: 15px"><%= comment.body %></p>
	<p style="font-size: 13px; color: gray">Created: <%= comment.created_at %></p>
	<hr /><br /> <br />
<% end %>

<% if user_signed_in? %>
	<h3><%= t('articles.add comment') %></h3>

	<%= form_for([@article, @article.comments.build]) do |f| %>

		<div>
			<%= f.text_area :body %>
		</div>	

		<br />

		<div>
			<%= f.submit %> <br />
		</div>	

	<% end %>

<% else %>
	<i>Please <%= link_to "sign in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %> to leave comments.</i>
<% end %>

<hr/>

app/views/contacts/create.html.erb
<h3>Thanks!</h3>

app/views/contacts/new.html.erb
<h3><%= t('contacts.contact_us') %></h3>

<%= form_for :contact , url: contacts_path do |f| %>

	<% if @contact && @contact.errors.any? %>
		<div>
		<ul>
			<% @contact.errors.full_messages.each do |mess| %>
				<li><%= mess %></li>
			<% end %>
		</ul>
		</div>
	<% end %>

	<div>
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</div>

	<br />

	<div>
		<%= f.label :message %> <br />
		<%= f.text_area :message %>
	</div>	

	<br />

	<div>
		<%= f.submit 'Send message' %> <br />
	</div>	

<% end %>

app/views/home/index.html.erb
<h3><%= t('index.hello') %></h3>

<p><%= t('index.welcome') %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link data-require="bootstrap@*" data-semver="4.0.5" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" />
    <script data-require="bootstrap@*" data-semver="4.0.5" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    

    <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
      
        <p class="navbar-text" style="width: 80px; text-align: center; background-color: #eee"><%= link_to t('articles.articles'), articles_path, class: "navbar-link" %></p>
        <p class="navbar-text" style="width: 80px; text-align: center; background-color: #eee"><%= link_to t('articles.new'), new_article_path %></p>
        <p class="navbar-text navbar-right" style="width: 80px; text-align: center; background-color: #eee">
            <% if user_signed_in? %>
            <%= t('user_welcome') %>, <%= current_user.username %> <%= link_to t('user auth.sign out'), destroy_user_session_path, method: :delete %> 
            <% else %>
            <%= link_to t('user auth.sign in'), new_user_session_path %>
            <%end%>
        </p>
      </div>
    </nav>

    <div class="container">
 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>

    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<h3>About us</h3>

app/views/pages/terms.html.erb
<h3>Terms of ...</h3>